package net.lax1dude.eaglercraft.v1_8.boot_menu.teavm;

/**
 * Copyright (c) 2024 lax1dude. All Rights Reserved.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 */
public class KeyCodes {

	public static final int DOM_KEY_SHIFT = 16;
	public static final int DOM_KEY_CONTROL = 17;
	public static final int DOM_KEY_ALT = 18;
	public static final int DOM_KEY_ENTER = 13;
	public static final int DOM_KEY_ESCAPE = 27;

	public static final int DOM_KEY_E = 69;
	public static final int DOM_KEY_SPACE = 32;

	public static final int DOM_KEY_ARROW_LEFT = 37;
	public static final int DOM_KEY_ARROW_UP = 38;
	public static final int DOM_KEY_ARROW_RIGHT = 39;
	public static final int DOM_KEY_ARROW_DOWN = 40;

}
